server:
  port: 6666

spring:
  application:
    name: seckill-eureka-server

eureka:
  instance:
    hostname: server
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server:6666/eureka/
